proxies:
  - name: "api"
    port: 7000
    target: "https://api.anthropic.com"
    
logging:
  showHeaders: true
  showBody: true
  showQuery: true
  showResponse: true
  maxBodyLength: 1000
  compact: false
  useColorTag: false